name: Test Suite
on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ['3.6', '3.8', '3.10', '3.12']
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install Dependencies
      run: |
        pip install tox
    - name: Run lint
      run: tox -vve lint
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ['3.6', '3.8', '3.10', '3.12']
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: |
          pip install tox
      - name: Run test
        run: tox -e unit
  integration-test:
    name: Integration test with LXD
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Read charmcraft version file
        id: charmcraft
        run: echo "channel=$(cat .charmcraft-channel)" >> $GITHUB_OUTPUT        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 3/stable
          charmcraft-channel: ${{ steps.charmcraft.outputs.channel }}
      - name: Run test
        run: tox -e integration
